name: flutter_application_1
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  dio: ^5.8.0+1
  path_provider: ^2.1.5
  ffi: ^2.1.4
  image_picker: ^1.0.7
  llama_cpp_dart:
    git:
      url: https://github.com/netdur/llama_cpp_dart.git

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  ffigen: ^20.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/chat_templates.json
  #   Native libraries (.so files) should be in android/app/src/main/jniLibs/
  #   not in assets folder
